// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVv4uQjGsY8QYSjf7Bebj9wMtNAuhG77M',
    appId: '1:655396072650:web:8da3d690f2706aec409833',
    messagingSenderId: '655396072650',
    projectId: 'swasthai-9ee70',
    authDomain: 'swasthai-9ee70.firebaseapp.com',
    storageBucket: 'swasthai-9ee70.firebasestorage.app',
    measurementId: 'G-TBPME26KZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLlWqbiuaWd0bDPjf775qzV7KgxWFpLpI',
    appId: '1:655396072650:android:efe9911d780e8cf2409833',
    messagingSenderId: '655396072650',
    projectId: 'swasthai-9ee70',
    storageBucket: 'swasthai-9ee70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZQSgRZY0yp904PbPwq95p0QpoMPQyRdw',
    appId: '1:655396072650:ios:48c281a1a7be7ed5409833',
    messagingSenderId: '655396072650',
    projectId: 'swasthai-9ee70',
    storageBucket: 'swasthai-9ee70.firebasestorage.app',
    iosBundleId: 'com.example.swasthai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZQSgRZY0yp904PbPwq95p0QpoMPQyRdw',
    appId: '1:655396072650:ios:48c281a1a7be7ed5409833',
    messagingSenderId: '655396072650',
    projectId: 'swasthai-9ee70',
    storageBucket: 'swasthai-9ee70.firebasestorage.app',
    iosBundleId: 'com.example.swasthai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVv4uQjGsY8QYSjf7Bebj9wMtNAuhG77M',
    appId: '1:655396072650:web:2fd6ce697eceb5e1409833',
    messagingSenderId: '655396072650',
    projectId: 'swasthai-9ee70',
    authDomain: 'swasthai-9ee70.firebaseapp.com',
    storageBucket: 'swasthai-9ee70.firebasestorage.app',
    measurementId: 'G-6TLW6Z5D65',
  );
}
