// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'Your Key',
    appId: 'Your ID',
    messagingSenderId: 'Your Credentials',
    projectId: 'swasthai',
    authDomain: 'swasthai-',
    storageBucket: 'swasthai-',
    measurementId: 'G-',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'Your Key',
    appId: 'Your Key',
    messagingSenderId: 'Your Key',
    projectId: 'Your Key',
    storageBucket: 'Your Key',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'Your Key',
    appId: 'Your Key',
    messagingSenderId: '6Your Key',
    projectId: 'Your Key',
    storageBucket: 'Your Key',
    iosBundleId: 'cYour Key',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'Your Key',
    appId: 'Your Key',
    messagingSenderId: 'Your Key',
    projectId: 'Your Key',
    storageBucket: 'sYour Keyp',
    iosBundleId: 'cYour Key',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'Your Key',
    appId: 'Your Key',
    messagingSenderId: 'Your Key',
    projectId: 'Your Key-Your Key',
    authDomain: 'Your Key Key9ee70.Your Key.com',
    storageBucket: 'Your Key-Your Key.Your Key.app',
    measurementId: 'G-Your Key',
  );
}
